language: cpp

dist: xenial
addons:
  apt:
    packages:
      - git
      - build-essential
      - gfortran
      - libopenmpi-dev
      - openmpi-bin
      - cmake-data
      - cmake
      - trilinos-all-dev
      - libx11-dev
      - x11proto-core-dev
      - libopenblas-dev
      - libhdf5-openmpi-dev
      # Manual Trilinos dependencies, which are bugged in 16.04
      - libmumps-dev
      - binutils-dev
      - libiberty-dev
      - libtbb-dev
      - libsuperlu-dev
      - libptscotch-dev

matrix:
  include:
    - os: linux
      env:
         - HYMLS_CMAKE_OPTIONS=""
    - os: linux
      env:
         - HYMLS_CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
    - os: linux
      env:
         - HYMLS_CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug -DHYMLS_DEBUGGING=ON"
    - os: linux
      env:
         - HYMLS_CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug -DHYMLS_LONG_LONG=ON"
    - os: linux
      env:
         - HYMLS_CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug -DHYMLS_TEST_NPROCS=1"

cache:
  ccache: true

install:
  - mkdir build
  - cd build
  - cmake ${HYMLS_CMAKE_OPTIONS} ..
  - make

script:
  - make check